"""cart item revision

Revision ID: 0f1c766eb739
Revises: f205cdcd43c4
Create Date: 2022-07-22 10:45:06.322209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1c766eb739'
down_revision = 'f205cdcd43c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'quanity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'quanity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
